name: 'build_and_test'
description: 'Build the project and test it'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

        - name: Cache dockerimage
          id: image-cache
          uses: actions/cache@v2
          with:
            path: ~/pythorch_cbt_devel.tar
            key: ${{ runner.os }}-docker-image-devel-${{ hashFiles('Dockerfile', '.dockerignore', 'install-cloud-sdk.sh') }}

        - name: Build the Docker image
          if: steps.image-cache.outputs.cache-hit != 'true'
          run: docker build -t pythorch_cbt_devel .

        - name: tar docker image
          if: steps.image-cache.outputs.cache-hit != 'true'
          run: docker save --output ~/pythorch_cbt_devel.tar pythorch_cbt_devel

        - name: load image
          if: steps.image-cache.outputs.cache-hit == 'true'
          run: docker load --input ~/pythorch_cbt_devel.tar

        - name: Run tests
          run: docker run --rm  --volume "`pwd`/plugin:/opt/pytorch" pythorch_cbt_devel /opt/pytorch/ci/check.sh
