name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: debugging
      run: docker load --help
    
    - uses: actions/checkout@v2
    
    - name: Cache dockerimage
      id: image-cache
      uses: actions/cache@v2
      with:
        path: ~/pythorch_cbt_devel.tar
        key: ${{ runner.os }}-pythorch_cbt_devel-${{ hashFiles('Dockerfile') }}
    
    - name: Build the Docker image
      if: steps.image-cache.outputs.cache-hit != 'true'
      run: docker build -t pythorch_cbt_devel .
    
    - name: tar docker image
      if: steps.image-cache.outputs.cache-hit != 'true'
      run: docker save --output pythorch_cbt_devel.tar pythorch_cbt_devel
      
    - name: load image
      if: steps.image-cache.outputs.cache-hit == 'true'
      run: docker load --input pythorch_cbt_devel.tar pythorch_cbt_devel
    
    - name: Run tests
#       run: docker run --rm  --volume "`pwd`/plugin:/opt/pytorch" pythorch_cbt_devel /opt/pytorch/ci/check.sh
      run: echo "Running tests!"

